name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit:
        description: '要构建的 Commit'
        required: true
        default: 'main'

jobs:
  build:
    name: Build Historical APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit || 'main' }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: placeholder.apk
          path: app/build/outputs/apk/debug/app-debug.apk
